### ISSUE TITLE
crashes when loading old worlds

### ISSUE THREAD

**Issue by shnenanigans** [Gregor0410/LazyStronghold#1]
It crashes and says this:

The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Cannot invoke "gregor0410.lazystronghold.StrongholdGen.start()" because the return value of "gregor0410.lazystronghold.ChunkGeneratorInterface.getStrongholdGen()" is null
Exit Code: -1

:(

**Comment by ronkzinho** [comment]
you are probably using seedqueue with this mod, use only this mod and I think u will be fine

**Comment by Gregor0410** [comment]
This bug should be resolved in release v1.0.3.
